name: Run test_transform_series tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  run-extract-variables-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pytest requests pandas

    - name: Run tests
      run: |
        PYTHONPATH=. pytest tests/etl_bcra/test_transform_series.py


